name: Build

on:
  push:
    branches-ignore:
      - experimental/**
      - master
  pull_request:
    branches-ignore:
      - experimental/**
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'

    - run: npm install
    - run: 'npm run test:unit --reporter=@danmasta/mocha-sonar --reporter-options --reporter=nyan,delimeter=::'
    - run: npm run build
